# Generated by Django 4.2 on 2023-04-04 10:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adherent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raisonsociale", models.CharField(max_length=45)),
                ("name", models.CharField(max_length=45)),
                ("prenom", models.CharField(max_length=45)),
                ("adresse", models.CharField(max_length=100)),
                ("codepostale", models.CharField(max_length=80)),
                ("ville", models.CharField(max_length=45)),
                ("numagresani", models.CharField(max_length=45)),
                ("coorets", models.IntegerField()),
                ("coorportable", models.IntegerField()),
                ("email", models.CharField(max_length=100)),
                ("siret", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "adherent",
            },
        ),
        migrations.CreateModel(
            name="Constatterrain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etatclaire", models.CharField(max_length=45)),
                ("date", models.DateField()),
                ("observation", models.TextField()),
                ("indicecondition", models.FloatField()),
            ],
            options={
                "db_table": "constatterrain",
            },
        ),
        migrations.CreateModel(
            name="Statutclaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "statutclaire",
            },
        ),
        migrations.CreateModel(
            name="Statutlieudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "statutlieudit",
            },
        ),
        migrations.CreateModel(
            name="Typeadherent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=45)),
                (
                    "idadherent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claire.adherent",
                    ),
                ),
            ],
            options={
                "db_table": "type_adherent",
            },
        ),
        migrations.CreateModel(
            name="Lieudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namelieudit", models.CharField(max_length=45)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("surface", models.FloatField()),
                (
                    "idstatutlieudit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claire.statutlieudit",
                    ),
                ),
            ],
            options={
                "db_table": "lieudit",
            },
        ),
        migrations.CreateModel(
            name="Claire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surface", models.FloatField()),
                ("codehydro", models.CharField(max_length=20)),
                (
                    "geomclai",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("nature", models.CharField(max_length=45)),
                ("numautorisationexploi", models.CharField(max_length=45)),
                ("nameclaire", models.CharField(max_length=45)),
                ("densitehuitre", models.FloatField()),
                ("dureeaffinage", models.FloatField()),
                ("source", models.CharField(max_length=45)),
                ("dateentree", models.DateField()),
                ("datesortie", models.DateField()),
                ("volume", models.FloatField()),
                ("salinite", models.FloatField()),
                ("quantbiomasse", models.FloatField()),
                ("profondeur", models.FloatField()),
                ("matieresuspension", models.FloatField()),
                ("tempearature", models.IntegerField()),
                ("dateacquisition", models.DateField()),
                ("ph", models.FloatField()),
                ("tauxsurvie", models.FloatField()),
                ("gainmassejournalier", models.FloatField()),
                ("poidsmoyinitial", models.FloatField()),
                ("poidsmoyfinal", models.FloatField()),
                (
                    "idconstatterrain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claire.constatterrain",
                    ),
                ),
                (
                    "idstatutclaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="claire.statutclaire",
                    ),
                ),
            ],
            options={
                "db_table": "claire",
            },
        ),
    ]
