# Generated by Django 4.2 on 2023-04-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("claire", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claire",
            name="idlieudit",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="claire.lieudit",
            ),
            preserve_default=False,
        ),
    ]
